# Enable C++ support
language: cpp
notifications:
  email: false

addons:
  apt_packages:
    - cmake
    - libxrandr-dev
    - libudev-dev
    - libopenal-dev
    - libflac-dev
    - libvorbis-dev
    - libgl1-mesa-dev

before_script:
- git clone -b '2.5.1' --depth 1 https://github.com/SFML/SFML.git sfml && cd sfml && mkdir build && cd build
- cmake .. $CMAKE_FLAGS -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=../install -DSFML_DEPENDENCIES_INSTALL_PREFIX=../install -DSFML_MISC_INSTALL_PREFIX=../install
- cmake --build . --target install
- cd ../..

script:
- mkdir build && cd build
- cmake .. -DBUILD_DEMO=ON -DBUILD_UNITTESTS=ON -DCMAKE_BUILD_TYPE=Release $CMAKE_FLAGS -DSFML_DIR=$TRAVIS_BUILD_DIR/sfml/install/lib/cmake/SFML -DCMAKE_INSTALL_PREFIX=../install
- cmake --build . --target install

matrix:
  include:

  - name: "Linux gcc"
    os: linux
    dist: xenial
    compiler: gcc

  - name: "Linux clang"
    os: linux
    dist: xenial
    compiler: clang

  - name: "MacOS clang"
    os: osx
    osx_image: xcode10
    compiler: clang

  - name: "Windows"
    os: windows
